apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DUMMY_CERTIFICATE_DATA
    server: https://DUMMY_SERVER
  name: dummy-cluster
contexts:
- context:
    cluster: dummy-cluster
    user: dummy-user
  name: dummy-context
current-context: dummy-context
kind: Config
preferences: {}
users:
- name: dummy-user
  user:
    token: DUMMY_TOKEN
